modules:
  - id: mode
    path: backend.modules.mode:ModeModule
    enabled: true
    critical: true

  - id: power_ignition
    path: backend.modules.power_ignition:IgnitionPowerModule
    enabled: true
    critical: true
    
  - id: power_work
    path: backend.modules.power_work:WorkPowerModule
    enabled: true
    critical: true

  - id: blower
    path: backend.modules.blower:BlowerModule
    enabled: true
    critical: true

  - id: feeder
    path: backend.modules.feeder:FeederModule
    enabled: true
    critical: true
    
  - id: mixer
    path: backend.modules.mixer:MixerModule
    enabled: true    
    critical: true

  - id: pump_cwu
    path: backend.modules.pump_cwu:CwuPumpModule
    enabled: true
    critical: true

  - id: pump_co
    path: backend.modules.pump_co:CoPumpModule
    enabled: true
    critical: true
   
   - id: stats
    path: backend.modules.stats:StatsModule
    enabled: true
    critical: true    
    
  - id: manual
    path: backend.modules.manual:ManualModule
    enabled: true
    critical: true

  - id: overheat
    path: backend.modules.overheat:OverheatModule
    enabled: true
    critical: true
    
  - id: safety
    path: backend.modules.safety:SafetyModule
    enabled: true
    critical: true

  - id: history
    path: backend.modules.history:HistoryModule
    enabled: true
    critical: false    
    
  - id: eventlog
    path: backend.modules.eventlog:EventLogModule
    enabled: true
    critical: false    
