modules:
  - id: blower
    path: backend.modules.blower:BlowerModule
    enabled: false
    critical: true

  - id: feeder
    path: backend.modules.feeder:FeederModule
    enabled: false
    critical: true

  - id: pump_cwu
    path: backend.modules.pump_cwu:CwuPumpModule
    enabled: true
    critical: true

  - id: pump_co
    path: backend.modules.pump_co:CoPumpModule
    enabled: true
    critical: true
    
  - id: mixer
    path: backend.modules.mixer:MixerModule
    enabled: false     # wyłączony, dopóki nie zaimplementujesz
    critical: true

  - id: history
    path: backend.modules.history:HistoryModule
    enabled: false
    critical: false    # historia nie jest krytyczna dla bezpieczeństwa
