adjust_interval_s: 60.0
boiler_max_drop_degC: 2.0
boiler_min_temp_for_open: 48.0
boiler_recover_factor: 1.0
max_pulse_s: 6.0
min_pulse_s: 1.0
ok_band_degC: 0.5
ramp_error_factor: 3.0
target_temp: 40.0
